### ISSUE TITLE
Unexpected syntax in moduleResolution node16

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1085]
The node16 moduleResolution in TypeScript expects the Blade package to be in CJS format due to lack of a `type: module` property in `package.json` but the syntax being shipped is ESM.

https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/9#issuecomment-1477125361

**Comment by divyanshu013** [comment]
Todo
- Should also be validated for React Native
- Check against various popular bundlers / build tools (eg parcel, vite)

**Comment by saurabhdaware** [comment]
Made a tiny attempt at this to make it work with Abell (it uses Vite so was facing this issue there) - https://github.com/razorpay/blade/pull/1144

This fixes the module issue but there is another issue in how we bundle which I didn't spend much time on - 
```
6:34:42 AM [vite] page reload App.tsx
TypeError: Cannot read properties of undefined (reading 'withConfig')
    at file:///project/sandbox/node_modules/@razorpay/blade/build/components/index.web.js:4497:39
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async nodeImport (file:///project/sandbox/node_modules/vite/dist/node/chunks/dep-561c5231.js:50364:21)
    at async eval (/App.tsx:4:31)
    at async instantiateModule (file:///project/sandbox/node_modules/vite/dist/node/chunks/dep-561c5231.js:50293:9)
```

Apparently, `styled.div` is coming as undefined in bundle. Example - 

https://codesandbox.io/p/sandbox/infallible-butterfly-872qpr?selection=%5B%7B%22endColumn%22%3A11%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A7%7D%5D&file=%2FApp.tsx
