### ISSUE TITLE
[Blade]: Fails when scaffolding with vite

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#429]
When running blade with vite setup it's throwing error: 

<img width="877" alt="Screenshot 2022-03-14 at 4 13 57 PM" src="https://user-images.githubusercontent.com/35374649/158156753-812b75fa-06a4-4866-97b5-8d53094ac1cc.png">

<details>

<summary>Log</summary>

Pre-bundling dependencies:
  react
  react-dom
  @razorpay/blade/components
  @razorpay/blade/tokens
  react/jsx-dev-runtime
(this will be run only when your dependencies or config have changed)
✘ [ERROR] Could not resolve "@babel/runtime-corejs3/helpers/defineProperty"

    node_modules/@razorpay/blade/build/components/index.web.js:1:30:
      1 │ import _defineProperty$1 from '@babel/runtime-corejs3/helpers/defineProperty';
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/helpers/defineProperty" as external to exclude it
  from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/helpers/typeof"

    node_modules/@razorpay/blade/build/components/index.web.js:2:20:
      2 │ import _typeof from '@babel/runtime-corejs3/helpers/typeof';
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/helpers/typeof" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/includes"

    node_modules/@razorpay/blade/build/components/index.web.js:3:38:
      3 │ import _includesInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/includes';
        ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/includes" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/keys"

    node_modules/@razorpay/blade/build/tokens/index.web.js:1:25:
      1 │ import _Object$keys from '@babel/runtime-corejs3/core-js-stable/object/keys';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/keys" as external to exclude
  it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/concat"

    node_modules/@razorpay/blade/build/components/index.web.js:4:36:
      4 │ import _concatInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/concat';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/concat" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols"

    node_modules/@razorpay/blade/build/tokens/index.web.js:2:42:
      2 │ ...t _Object$getOwnPropertySymbols from '@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols';
        ╵                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols" as
  external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/keys"

    node_modules/@razorpay/blade/build/components/index.web.js:5:25:
      5 │ import _Object$keys from '@babel/runtime-corejs3/core-js-stable/object/keys';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/keys" as external to exclude
  it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/filter"

    node_modules/@razorpay/blade/build/tokens/index.web.js:3:36:
      3 │ import _filterInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/filter';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/filter" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols"

    node_modules/@razorpay/blade/build/components/index.web.js:6:42:
      6 │ ...t _Object$getOwnPropertySymbols from '@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols';
        ╵                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols" as
  external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptor"

    node_modules/@razorpay/blade/build/tokens/index.web.js:4:45:
      4 │ ...ect$getOwnPropertyDescriptor from '@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptor';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptor"
  as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/filter"

    node_modules/@razorpay/blade/build/components/index.web.js:7:36:
      7 │ import _filterInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/filter';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/filter" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/for-each"

    node_modules/@razorpay/blade/build/tokens/index.web.js:5:37:
      5 │ import _forEachInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/for-each';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/for-each" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptor"

    node_modules/@razorpay/blade/build/components/index.web.js:8:45:
      8 │ ...ect$getOwnPropertyDescriptor from '@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptor';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptor"
  as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptors"

    node_modules/@razorpay/blade/build/tokens/index.web.js:6:46:
      6 │ ...t$getOwnPropertyDescriptors from '@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptors';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptors"
  as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/for-each"

    node_modules/@razorpay/blade/build/components/index.web.js:9:37:
      9 │ import _forEachInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/for-each';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/for-each" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/define-properties"

    node_modules/@razorpay/blade/build/tokens/index.web.js:7:37:
      7 │ import _Object$defineProperties from '@babel/runtime-corejs3/core-js-stable/object/define-properties';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/define-properties" as external
  to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptors"

    node_modules/@razorpay/blade/build/components/index.web.js:10:46:
      10 │ ...$getOwnPropertyDescriptors from '@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptors';
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/get-own-property-descriptors"
  as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/define-property"

    node_modules/@razorpay/blade/build/tokens/index.web.js:8:35:
      8 │ import _Object$defineProperty from '@babel/runtime-corejs3/core-js-stable/object/define-property';
        ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/define-property" as external
  to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/define-properties"

    node_modules/@razorpay/blade/build/components/index.web.js:11:37:
      11 │ import _Object$defineProperties from '@babel/runtime-corejs3/core-js-stable/object/define-properties';
         ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/define-properties" as external
  to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/helpers/defineProperty"

    node_modules/@razorpay/blade/build/tokens/index.web.js:9:30:
      9 │ import _defineProperty$1 from '@babel/runtime-corejs3/helpers/defineProperty';
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/helpers/defineProperty" as external to exclude it
  from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/define-property"

    node_modules/@razorpay/blade/build/components/index.web.js:12:35:
      12 │ import _Object$defineProperty from '@babel/runtime-corejs3/core-js-stable/object/define-property';
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/define-property" as external
  to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/helpers/typeof"

    node_modules/@razorpay/blade/build/tokens/index.web.js:10:20:
      10 │ import _typeof from '@babel/runtime-corejs3/helpers/typeof';
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/helpers/typeof" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/helpers/slicedToArray"

    node_modules/@razorpay/blade/build/components/index.web.js:13:27:
      13 │ import _slicedToArray from '@babel/runtime-corejs3/helpers/slicedToArray';
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/helpers/slicedToArray" as external to exclude it
  from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/helpers/slicedToArray"

    node_modules/@razorpay/blade/build/tokens/index.web.js:11:27:
      11 │ import _slicedToArray from '@babel/runtime-corejs3/helpers/slicedToArray';
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/helpers/slicedToArray" as external to exclude it
  from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/entries"

    node_modules/@razorpay/blade/build/components/index.web.js:14:7:
      14 │ import '@babel/runtime-corejs3/core-js-stable/object/entries';
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/entries" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/object/entries"

    node_modules/@razorpay/blade/build/tokens/index.web.js:12:29:
      12 │ import _Object$entries2 from '@babel/runtime-corejs3/core-js-stable/object/entries';
         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/object/entries" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/array/is-array"

    node_modules/@razorpay/blade/build/components/index.web.js:15:7:
      15 │ import '@babel/runtime-corejs3/core-js-stable/array/is-array';
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/array/is-array" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/array/is-array"

    node_modules/@razorpay/blade/build/tokens/index.web.js:13:27:
      13 │ import _Array$isArray from '@babel/runtime-corejs3/core-js-stable/array/is-array';
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/array/is-array" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/json/stringify"

    node_modules/@razorpay/blade/build/components/index.web.js:16:7:
      16 │ import '@babel/runtime-corejs3/core-js-stable/json/stringify';
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/json/stringify" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/concat"

    node_modules/@razorpay/blade/build/tokens/index.web.js:14:36:
      14 │ import _concatInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/concat';
         ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/concat" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/every"

    node_modules/@razorpay/blade/build/components/index.web.js:17:7:
      17 │ import '@babel/runtime-corejs3/core-js-stable/instance/every';
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/every" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/json/stringify"

    node_modules/@razorpay/blade/build/tokens/index.web.js:15:28:
      15 │ import _JSON$stringify from '@babel/runtime-corejs3/core-js-stable/json/stringify';
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/json/stringify" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/map"

    node_modules/@razorpay/blade/build/components/index.web.js:18:33:
      18 │ import _mapInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/map';
         ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/map" as external to exclude
  it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/every"

    node_modules/@razorpay/blade/build/tokens/index.web.js:16:35:
      16 │ import _everyInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/every';
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/every" as external to
  exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/slice"

    node_modules/@razorpay/blade/build/components/index.web.js:19:35:
      19 │ import _sliceInstanceProperty from '@babel/runtime-corejs3/core-js-stable/instance/slice';
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/instance/slice" as external to
  exclude it from the bundle, which will remove this error.

error when starting dev server:
Error: Build failed with 35 errors:
node_modules/@razorpay/blade/build/components/index.web.js:1:30: ERROR: Could not resolve "@babel/runtime-corejs3/helpers/defineProperty"
node_modules/@razorpay/blade/build/components/index.web.js:2:20: ERROR: Could not resolve "@babel/runtime-corejs3/helpers/typeof"
node_modules/@razorpay/blade/build/components/index.web.js:3:38: ERROR: Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/includes"
node_modules/@razorpay/blade/build/components/index.web.js:4:36: ERROR: Could not resolve "@babel/runtime-corejs3/core-js-stable/instance/concat"
node_modules/@razorpay/blade/build/components/index.web.js:5:25: ERROR: Could not resolve "@babel/runtime-corejs3/core-js-stable/object/keys"
...
    at failureErrorWithLog (/Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:1605:15)
    at /Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:1251:28
    at runOnEndCallbacks (/Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:1036:63)
    at buildResponseToResult (/Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:1249:7)
    at /Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:1358:14
    at /Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:668:9
    at handleIncomingPacket (/Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:765:9)
    at Socket.readFromStdout (/Users/anurag.hazra/Documents/razorpay/experiments/test-blade-tokens/node_modules/esbuild/lib/main.js:635:7)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)

</details>

**Comment by saurabhdaware** [comment]
Also happens when trying to install with `react-scripts` https://codesandbox.io/s/blade-no-runtime-corejs3-issue-cohnk6?file=/src/App.tsx
